version: "3.8"

services:
  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: sh -c "sleep 30 && python3 telegram-bot-main.py"
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      SESSION_NAME_BOT: ${SESSION_NAME_BOT}
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      BOT_TOKEN: ${BOT_TOKEN}
      MODEL_ENGINE: ${MODEL_ENGINE}
      OPENAI_KEY: ${OPENAI_KEY}
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
